// src/config/dotenvXConfig.js
const dotEnvX = require('@dotenvx/dotenvx');
dotEnvX.config()
module.exports = {
    HOST: process.env.HOST || 'NO ENCONTRE VARIABLE DE ENTORNO',
    PORT: process.env.PORT || 'NO ENCONTRE PORT',
    API_URL: process.env.API_URL || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    CONNECTION_STRING: process.env.CONNECTION_STRING || 'NO SE ENCONTRO VARIABLE DE ENTORNO', 
    DATABASE: process.env.DATABASE || 'NO SE ENCONTRO VARIABLE DE ENTORNO',  
    DB_USER: process.env.DB_USER || 'NO SE ENCONTRO VARIABLE DE ENTORNO',  
    DB_PASSWORD: process.env.DB_PASSWORD || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    COSMOSDB_ENDPOINT: process.env.COSMOSDB_ENDPOINT || 'NO SE ENCONTRO ENDPOINT PARA COSMOS DB',
    COSMOSDB_KEY: process.env.COSMOSDB_KEY || 'NO SE ENCONTRO KEY PARA COSMOS DB',
    COSMOSDB_CONTAINER: process.env.COSMOSDB_CONTAINER || 'NO SE ENCONTRO CONTAINER PARA COSMOS DB'
};